networks:
  kyc-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16
services:
  decision-agent:
    build:
      context: ./python-agents/decision-orchestration-agent
      dockerfile: Dockerfile
    container_name: kyc-decision-agent
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_DB=${POSTGRES_DB:-kyc_db}
    - POSTGRES_USER=${POSTGRES_USER:-postgres}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    - OPENAI_API_KEY=${OPENAI_API_KEY}
    - REQUIRE_AUTH=${REQUIRE_AUTH:-false}
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8003/health
      timeout: 10s
    hostname: decision-agent
    networks:
    - kyc-network
    restart: unless-stopped
  intake-agent:
    build:
      context: ./python-agents/intake-processing-agent
      dockerfile: Dockerfile
    container_name: kyc-intake-agent
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_DB=${POSTGRES_DB:-kyc_db}
    - POSTGRES_USER=${POSTGRES_USER:-postgres}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    - OPENAI_API_KEY=${OPENAI_API_KEY}
    - VISION_MODEL=${VISION_MODEL:-gpt-4-vision-preview}
    - REQUIRE_AUTH=${REQUIRE_AUTH:-false}
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8001/health
      timeout: 10s
    hostname: intake-agent
    networks:
    - kyc-network
    restart: unless-stopped
  intelligence-agent:
    build:
      context: ./python-agents/intelligence-compliance-agent
      dockerfile: Dockerfile
    container_name: kyc-intelligence-agent
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_DB=${POSTGRES_DB:-kyc_db}
    - POSTGRES_USER=${POSTGRES_USER:-postgres}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - QDRANT_HOST=qdrant
    - QDRANT_PORT=6333
    - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    - OPENAI_API_KEY=${OPENAI_API_KEY}
    - REQUIRE_AUTH=${REQUIRE_AUTH:-false}
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8002/health
      timeout: 10s
    hostname: intelligence-agent
    networks:
    - kyc-network
    restart: unless-stopped
  postgres:
    container_name: kyc-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kyc_db}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    healthcheck:
      interval: 10s
      retries: 5
      test:
      - CMD-SHELL
      - pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-kyc_db}
      timeout: 5s
    hostname: postgres
    image: postgres:15-alpine
    networks:
    - kyc-network
    ports:
    - 5433:5432
    restart: unless-stopped
    volumes:
    - postgres-data:/var/lib/postgresql/data
    - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  qdrant:
    container_name: kyc-qdrant
    environment:
    - QDRANT__SERVICE__HTTP_PORT=6333
    - QDRANT__SERVICE__GRPC_PORT=6334
    - QDRANT__LOG_LEVEL=INFO
    hostname: qdrant
    image: qdrant/qdrant:v1.7.4
    networks:
    - kyc-network
    ports:
    - 6335-6336:6333-6334
    restart: unless-stopped
    volumes:
    - qdrant-data:/qdrant/storage
  redis:
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    container_name: kyc-redis
    healthcheck:
      interval: 10s
      retries: 5
      test:
      - CMD
      - redis-cli
      - ping
      timeout: 5s
    hostname: redis
    image: redis:7-alpine
    networks:
    - kyc-network
    ports:
    - 6380:6379
    restart: unless-stopped
    volumes:
    - redis-data:/data
  web-interface:
    build:
      context: ./rust-core
      dockerfile: Dockerfile
    container_name: kyc-web-interface
    depends_on:
      decision-agent:
        condition: service_healthy
      intake-agent:
        condition: service_healthy
      intelligence-agent:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
    - SERVER_HOST=0.0.0.0
    - SERVER_PORT=8000
    - POSTGRES_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-kyc_db}
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_DB=${POSTGRES_DB:-kyc_db}
    - POSTGRES_USER=${POSTGRES_USER:-postgres}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    - REDIS_URL=redis://redis:6379
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - QDRANT_HOST=qdrant
    - QDRANT_PORT=6333
    - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
    - RUST_LOG=${RUST_LOG:-info}
    - REQUIRE_AUTH=${REQUIRE_AUTH:-false}
    - INTAKE_AGENT_URL=http://intake-agent:8001
    - INTELLIGENCE_AGENT_URL=http://intelligence-agent:8002
    - DECISION_AGENT_URL=http://decision-agent:8003
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8000/health
      timeout: 10s
    hostname: web-interface
    networks:
    - kyc-network
    ports:
    - ${KYC_PORT:-8000}:8000
    restart: unless-stopped
volumes:
  postgres-data:
    driver: local
  qdrant-data:
    driver: local
  redis-data:
    driver: local
