# Prometheus Configuration for ComplianceAI
# This configuration monitors all ComplianceAI services and infrastructure

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'
rule_files:
  - "alert_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    scrape_timeout: 10s

  # ComplianceAI Web Interface
  - job_name: 'complianceai-web'
    static_configs:
      - targets:
        - 'web-interface:8000'
        - 'web-interface-1:8000'
        - 'web-interface-2:8000'
        - 'web-interface-3:8000'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*):.*'
        replacement: '${1}'
    http_config:
      tls_config:
        insecure_skip_verify: true

  # Regulatory Intelligence Agent
  - job_name: 'complianceai-regintel'
    static_configs:
      - targets: ['regulatory-intelligence:8001']
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  # Intelligence & Compliance Agent
  - job_name: 'complianceai-intelcomp'
    static_configs:
      - targets: ['intelligence-compliance:8002']
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  # Decision & Orchestration Agent
  - job_name: 'complianceai-decision'
    static_configs:
      - targets: ['decision-orchestration:8003']
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  # Intake & Processing Agent
  - job_name: 'complianceai-intake'
    static_configs:
      - targets: ['intake-processing:8004']
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # MongoDB Database
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:9216']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Apache Kafka
  - job_name: 'kafka'
    static_configs:
      - targets:
        - 'kafka:7071'
        - 'kafka-1:7071'
        - 'kafka-2:7071'
    scrape_interval: 30s
    scrape_timeout: 15s

  # Zookeeper
  - job_name: 'zookeeper'
    static_configs:
      - targets:
        - 'zookeeper:9141'
        - 'zookeeper-1:9141'
        - 'zookeeper-2:9141'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx Load Balancer
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter (System Metrics)
  - job_name: 'node'
    static_configs:
      - targets:
        - 'node-exporter:9100'
        - 'web-interface:9100'
        - 'postgres:9100'
        - 'mongodb:9100'
        - 'redis:9100'
        - 'kafka:9100'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker Container Metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Pushgateway for Batch Jobs
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # Blackbox Exporter for External Services
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.eba.europa.eu/health
        - https://www.federalreserve.gov
        - https://www.fca.org.uk
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom Business Metrics
  - job_name: 'complianceai-business'
    static_configs:
      - targets: ['web-interface:8000']
    scrape_interval: 60s
    scrape_timeout: 30s
    metrics_path: '/business-metrics'
    params:
      format: ['prometheus']

# Remote write configuration (optional)
# remote_write:
#   - url: "https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push"
#     basic_auth:
#       username: "<username>"
#       password: "<password>"

# Remote read configuration (optional)
# remote_read:
#   - url: "https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom"
#     basic_auth:
#       username: "<username>"
#       password: "<password>"
